version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: unilab
      MYSQL_USER: unilab
      MYSQL_PASSWORD: unilabpwd
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode="]

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: unilab
      DB_PASSWORD: unilabpwd
      DB_NAME: unilab
    depends_on:
      - db

  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
